name: 'CI-CD Terraform destroy'

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "yes" to confirm destruction'
        required: true
        default: 'no'

permissions:
  contents: read

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-1'

jobs:
  terraform_static_analysis:
    name: 'Terraform Static Analysis'
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  terraform_destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    needs: terraform_static_analysis
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.confirmation == 'yes'
    steps:
      - uses: actions/checkout@v2

      - name: Terraform Destroy
        working-directory: terraform 
        run: |
          terraform init  
          terraform destroy --target=aws_route53_record.tm_cname_record --auto-approve
          terraform destroy --auto-approve 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'

      - name: Send Discord Notification on Success destroy
        if: success()
        run: |
            BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
            TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
            COMMITTER=${GITHUB_ACTOR}
            curl -H "Content-Type: application/json" \
            -d "{\"content\": \"âœ… Application built destroyed: in repo ${{ github.event.repository.name }}, ${BRANCH_NAME} at ${TIMESTAMP}. Committer: ${COMMITTER}\"}" \
             ${{ secrets.DISCORD_WEBHOOK_URL }}
             